# Generated by Django 5.1.1 on 2024-09-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universitet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
